### ISSUE TITLE
[Bug]: Advancements are referred to as "achievements" in the messageFormatting config section.

### ISSUE THREAD

**Issue by DorkOrc** [hypherionmc/sdlink#154]
### 🐞 Description

This should be "advancements" and the description should say "Advancement Messages":
```toml
[messageFormatting]
	#Achievement Messages. Available variables: %player%, %title%, %description%
	achievements = "..."
```

The term "achievements" is not used by Minecraft, and having it use the wrong word can make it harder to search for advancement-related settings in the config file.

### 🔄 Steps to reproduce

1. Open the default config file
2. Search for "achievement"

### ✅ Expected behavior

It should refer to these messages as "Advancement Messages"

### ❌ Actual behavior

Instead, it calls them "Achievement Messages"

### 🎮 Minecraft Version

1.21.5-pre2

### 🛠️ Mod Version

SimpleDiscordLink-Universal-3.3.0+snapshot.2

### 📦 Mod Loader

Fabric

### 🔧 Mod Loader Version

n/a

### 📚 CraterLib Version

CraterLib-Fabric-25w10a-2.1.4+experimental.0
