### ISSUE TITLE
[Bug]: Issues on startup, something about a "moonconfig"

### ISSUE THREAD

**Issue by Extreme1106** [hypherionmc/sdlink#163]
### 🐞 Description

Hello, I have been using this mod for quite a while and everything has been going well ever since my last issue was resolved until about 2 days ago, when these errors popped up after updating from 1.21.3 to 1.21.4. I am using an SSH so I couldn't copy and paste the lines and resorted to screenshotting them instead:

![Image](https://github.com/user-attachments/assets/4304a2d8-0500-414c-930b-779cb195e99e)
![Image](https://github.com/user-attachments/assets/f79e899c-9fea-4a65-97cd-7495a0d5c7d5)
![Image](https://github.com/user-attachments/assets/1a122b3e-97e0-4e01-af21-d93ecc1cfe06)
Any help with this issue ASAP is greatly appreciated

### 🔄 Steps to reproduce

Launching the server

### ✅ Expected behavior

The server/bot boots up as normal (the bot doesn't go online of course)

### ❌ Actual behavior

An error occurs and the server shuts itself down

### 🎮 Minecraft Version

1.21.4

### 🛠️ Mod Version

3.3.0

### 📦 Mod Loader

Fabric

### 🔧 Mod Loader Version

0.16.14

### 📚 CraterLib Version

1.21.3-2.1.4

### 📜 Logs & Screenshots

![Image](https://github.com/user-attachments/assets/de1cedb6-f330-4625-9a90-cd1fc6aac8cf)
![Image](https://github.com/user-attachments/assets/b0ff737f-95e3-4b06-bff2-7c1366acb37c)
![Image](https://github.com/user-attachments/assets/c2ef1658-8487-4ae6-814e-24b1dd175a27)

**Comment by hypherionmc** [comment]
This is a confusing one.

It *looks* like an issue with the config file it's trying to load (which wouldn't make sense, if you only upgraded your MC version).

Make a copy of your configs, and let the mod generate a completely new one. If it doesn't crash then, please send a copy of your old config, so I can look for any possible errors.

If it still crashes, then this will be a fun one to solve

**Comment by Extreme1106** [comment]
I deleted every config per your instructions and, well, it seems to give the same error

![Image](https://github.com/user-attachments/assets/10aae7af-6c17-4ac8-98f7-27db594d5053)

**Comment by Extreme1106** [comment]
also I tried deleting both simple discord link and craterlib from my .mrpack but for some reason craterlib and sdlink both show up still when starting the server and it always gives that same error whenever I start it, so now it's just kinda impossible to start at all until I figure this or that out

**Comment by hypherionmc** [comment]
Sorry for the delay. Was a hectic day at work.

Do you maybe have a copy of your modpack I can use for testing?

**Comment by Extreme1106** [comment]
it says I'm not allowed to link the files here so I'm using a Discord link, this is made using Modrinth https://cdn.discordapp.com/attachments/1298134293670924308/1365044393094025336/ExtremeSMP_1.0.0.mrpack?ex=680be028&is=680a8ea8&hm=018bbd5e0618b4d89307aa3fde41febb102bcb87881f9bde25e363c490ea9572&

**Comment by hypherionmc** [comment]
So this is interesting. 

I tried installing your modpack locally to test, and I got this:

```
Loading Fabric Installer: 1.0.1
Installing Fabric Loader 1.21.4+0.16.14(1.21.4) on the server
Downloading required files
service FabricService{meta='https://meta.fabricmc.net/', maven='https://maven.fabricmc.net/'} failed: java.io.IOException: HTTP request to https://meta.fabricmc.net/v2/versions/loader/1.21.4/1.21.4+0.16.14/server/json failed: 400
service FabricService{meta='https://meta2.fabricmc.net/', maven='https://maven2.fabricmc.net/'} failed: java.io.IOException: HTTP request to https://meta2.fabricmc.net/v2/versions/loader/1.21.4/1.21.4+0.16.14/server/json failed: 400
service FabricService{meta='https://meta3.fabricmc.net/', maven='https://maven3.fabricmc.net/'} failed: java.io.IOException: HTTP request to https://meta3.fabricmc.net/v2/versions/loader/1.21.4/1.21.4+0.16.14/server/json failed: 400
```

Opening the fabric URL in my browser, gives me this: `no loader version found for 1.21.4`, so this looks like a fabric issue

**Comment by Extreme1106** [comment]
That's weird, when I run the modpack back on 0.14.9 which is the original fabric loader I used the same error is given, I also was able to launch the server on both versions before but some issue specifically with sdlink is occurring which is when all this stuff began, I even tried re-adding my Discord bot to my server with all the proper permissions intact but it still doesn't come online at all, what do you think I should do to narrow down the reasons why this could be happening?

**Comment by SirPotato42** [comment]
I am experiencing the same issue. I run the stack deobfuscator mod (https://modrinth.com/mod/stackdeobf) to make it easier to read the crash, this is what I get:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'sdlink' at 'com.hypherionmc.sdlink.loaders.fabric.SDLinkFabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:64) ~[fabric-loader-0.16.13.jar:?]
	at knot/net.minecraft.server.Main.main(Main.java:113) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.13.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.5-loader.0.16.13-launcher.1.0.3.jar:1.0.3]
Caused by: java.lang.ClassCastException: class shadow.hypherionmc.moonconfig.core.SimpleCommentedConfig cannot be cast to class [Ljava.lang.Object; (shadow.hypherionmc.moonconfig.core.SimpleCommentedConfig is in unnamed module of loader 'knot' @77caeb3e; [Ljava.lang.Object; is in module java.base of loader 'bootstrap')
	at knot/com.hypherionmc.sdlink.core.config.SDLinkConfig.lambda$updateConfigValues$0(SDLinkConfig.java:202) ~[SimpleDiscordLink-Universal-3.3.0.jar:?]
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986) ~[?:?]
	at knot/com.hypherionmc.sdlink.core.config.SDLinkConfig.updateConfigValues(SDLinkConfig.java:197) ~[SimpleDiscordLink-Universal-3.3.0.jar:?]
	at knot/com.hypherionmc.sdlink.core.config.SDLinkConfig.lambda$updateConfigValues$0(SDLinkConfig.java:235) ~[SimpleDiscordLink-Universal-3.3.0.jar:?]
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986) ~[?:?]
	at knot/com.hypherionmc.sdlink.core.config.SDLinkConfig.updateConfigValues(SDLinkConfig.java:197) ~[SimpleDiscordLink-Universal-3.3.0.jar:?]
	at knot/com.hypherionmc.sdlink.core.config.SDLinkConfig.migrateConfig(SDLinkConfig.java:120) ~[SimpleDiscordLink-Universal-3.3.0.jar:?]
	at knot/com.hypherionmc.sdlink.core.config.SDLinkConfig.registerAndSetup(SDLinkConfig.java:98) ~[SimpleDiscordLink-Universal-3.3.0.jar:?]
	at knot/com.hypherionmc.sdlink.core.config.SDLinkConfig.<init>(SDLinkConfig.java:88) ~[SimpleDiscordLink-Universal-3.3.0.jar:?]
	at knot/com.hypherionmc.sdlink.core.discord.BotController.<init>(BotController.java:75) ~[SimpleDiscordLink-Universal-3.3.0.jar:?]
	at knot/com.hypherionmc.sdlink.core.discord.BotController.newInstance(BotController.java:106) ~[SimpleDiscordLink-Universal-3.3.0.jar:?]
	at knot/com.hypherionmc.sdlink.server.ServerEvents.<init>(ServerEvents.java:67) ~[SimpleDiscordLink-Universal-3.3.0.jar:?]
	at knot/com.hypherionmc.sdlink.server.ServerEvents.getInstance(ServerEvents.java:61) ~[SimpleDiscordLink-Universal-3.3.0.jar:?]
	at knot/com.hypherionmc.sdlink.loaders.fabric.SDLinkFabric.onInitializeServer(SDLinkFabric.java:17) ~[SimpleDiscordLink-Universal-3.3.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.13.jar:?]
	... 7 more
```

**Comment by meza** [comment]
Getting the same issue too

**Comment by hypherionmc** [comment]
Are you all on 1.21.4?

**Comment by meza** [comment]
1.21.5 for me, just updated the server. sdlink 3.3.0

Downgrading to 3.2.3 worked

**Comment by hypherionmc** [comment]
Okay, sounds like a bug in the config migrator.

**Comment by hypherionmc** [comment]
Can you send me a copy of your config without the token and webhook urls, so I can test

**Comment by meza** [comment]
Unfortunately gh doesn't allow toml files to be uploaded.

I've changed the role ids just in case

```toml
#General Mod Config
[general]
#Should the mod be enabled or not
enabled = true
#Enable Additional Logging. Used for Fault Finding. WARNING: CAUSES LOG SPAM!
debugging = true
#Internal version control. DO NOT TOUCH!
configVersion = 13

#Config specific to the discord bot
[botConfig]
#The token of the Discord Bot to use. This will be encrypted on first load. See https://sdlink.fdd-docs.com/initial-setup/ to find this
botToken = "DISCORD_TOKEN_REPLACE"
#How often the Bot Status will update on Discord (in Seconds). Set to 0 to disable
statusUpdateInterval = 30

#Control what the Discord Bot will display as it's status message
[botConfig.botStatus]
#Do not add Playing. A status to display on the bot. You can use %players% and %maxplayers% to show the number of players on the server
status = "Mezacraft with %players%/%maxplayers% players"
#The type of the status displayed on the bot. Valid entries are: PLAYING, STREAMING, WATCHING, LISTENING, CUSTOM_STATUS
botStatusType = "CUSTOM_STATUS"
#The URL that will be used when the "botStatusType" is set to "STREAMING", required to display as "streaming".
botStatusStreamingURL = "https://twitch.tv/houseofmeza"

#Define how the bot should handle channel topic updates on the chat channel
[botConfig.topicUpdates]
#Should the bot update the topic of your chat channel automatically every 6 Minutes
doTopicUpdates = true
#A topic for the Chat Relay channel. You can use %player%, %maxplayers%, %uptime% or just leave it empty.
channelTopic = "Mezacraft with %players%/%maxplayers% people | Uptime: %uptime%"

#Configure the in-game Discord Invite command
[botConfig.invite]
#If this is defined, it will enable the in-game Discord command
inviteLink = "https://discord.gg/mezanites"
#The message to show when someone uses /discord command. You can use %inviteurl%
inviteMessage = "Hey, check out our discord server here -> %inviteurl%"

#Config relating to the discord channels and webhooks to use with the mod
[channelsAndWebhooks]
#A DIRECT link to an image to use as the avatar for server messages. Also used for embeds
serverAvatar = ""
#The name to display for Server messages when using Webhooks
serverName = "Mezacraft Server"

#Config relating to the discord channels to use with the mod
[channelsAndWebhooks.channels]
#REQUIRED! The ID of the channel to post in and relay messages from. This is still needed, even in webhook mode
chatChannelID = "DISCORD_CHAT_CHANNEL_REPLACE"
#If this ID is set, event messages will be posted in this channel instead of the chat channel
eventsChannelID = "DISCORD_EVENTS_CHANNEL_REPLACE"
#If this ID is set, console messages sent after the bot started will be relayed here
consoleChannelID = "0"

#Config relating to the discord Webhooks to use with the mod
[channelsAndWebhooks.webhooks]
#Prefer Webhook Messages over Standard Bot Messages
enabled = false
#The URL of the channel webhook to use for Chat Messages. Will be encrypted on first run
chatWebhook = ""
#The URL of the channel webhook to use for Server Messages. Will be encrypted on first run
eventsWebhook = ""
#The URL of the channel webhook to use for Console Messages. DOES NOT WORK FOR CONSOLE RELAY! Will be encrypted on first run
consoleWebhook = ""

#Configure which types of messages are delivered to Minecraft/Discord
[chat]
#Use linked account names in Discord/Minecraft messages, instead of the default ones
useLinkedNames = true
#Convert Discord to MC, and MC to Discord Formatting
formatting = true
#Should console messages be sent to the Console Channel
sendConsoleMessages = false
#The type of image to use as the player icon in messages. Valid entries are: AVATAR, HEAD, BODY, COMBO
playerAvatarType = "HEAD"
#Should messages sent with TellRaw be sent to discord as a chat? (Experimental)
relayTellRaw = false
#Should the entire command executed be relayed to discord, or only the name of the command
relayFullCommands = false
#Should messages from bots be relayed
ignoreBots = true
#Should SERVER STARTING messages be shown
serverStarting = true
#Should SERVER STARTED messages be shown
serverStarted = true
#Should SERVER STOPPING messages be shown
serverStopping = true
#Should SERVER STOPPED messages be shown
serverStopped = true
#Should the chat be relayed
playerMessages = true
#Should Player Join messages be posted
playerJoin = true
#Should Player Leave messages be posted
playerLeave = true
#Should Advancement messages be posted
advancementMessages = true
#Should Death Announcements be posted
deathMessages = true
#Should Messages from the /say command be posted
sendSayCommand = true
#Should commands be posted to discord
broadcastCommands = false
#Commands that should not be broadcast to discord
ignoredCommands = ["particle", "login", "execute", "tellraw", "save-all", "stop", "script"]
#Allow mentioning discord roles, users and channels from Minecraft Chat
allowMentionsFromChat = false

#Change the format in which messages are displayed
[messageFormatting]
#Prefix to add to Minecraft when a message is relayed from Discord. Supports MC formatting. Use %user% for the Discord Username
mcPrefix = "§e[Discord]§r %user%: "
#Server Starting Message
serverStarting = "*Server is starting...*"
#Server Started Message
serverStarted = "*Server has started. Enjoy!*"
#Server Stopping Message
serverStopping = "*Server is stopping...*"
#Server Stopped Message
serverStopped = "*Server has stopped...*"
#Player Joined Message. Use %player% to display the player name
playerJoined = "*%player% has joined the server!*"
#Player Left Message. Use %player% to display the player name
playerLeft = "*%player% has left the server!*"
#Achievement Messages. Available variables: %player%, %title%, %description%
achievements = "*%player% has made the advancement [%title%]: %description%*"
#Chat Messages. THIS DOES NOT APPLY TO EMBED OR WEBHOOK MESSAGES. Available variables: %player%, %message%
chat = "%player%: %message%"
#Death Messages. Available variables: %player%, %message%
death = "%player% %message%"
#Command Messages. Available variables: %player%, %command%
commands = "%player% **executed command**: *%command%*"

#Change in which channel messages appear
[messageDestinations]

#Control where CHAT messages are delivered
[messageDestinations.chat]
#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
channel = "CHAT"
#Should the message be sent using EMBED style messages
useEmbed = true
#Embed Layout to use
embedLayout = "default"

#Control where START messages are delivered
[messageDestinations.start]
#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
channel = "EVENT"
#Should the message be sent using EMBED style messages
useEmbed = true
#Embed Layout to use
embedLayout = "default"

#Control where STOP messages are delivered
[messageDestinations.stop]
#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
channel = "EVENT"
#Should the message be sent using EMBED style messages
useEmbed = true
#Embed Layout to use
embedLayout = "default"

#Control where JOIN messages are delivered
[messageDestinations.join]
#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
channel = "EVENT"
#Should the message be sent using EMBED style messages
useEmbed = true
#Embed Layout to use
embedLayout = "default"

#Control where LEAVE messages are delivered
[messageDestinations.leave]
#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
channel = "EVENT"
#Should the message be sent using EMBED style messages
useEmbed = true
#Embed Layout to use
embedLayout = "default"

#Control where ADVANCEMENT messages are delivered
[messageDestinations.advancements]
#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
channel = "EVENT"
#Should the message be sent using EMBED style messages
useEmbed = false
#Embed Layout to use
embedLayout = "default"

#Control where DEATH messages are delivered
[messageDestinations.death]
#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
channel = "EVENT"
#Should the message be sent using EMBED style messages
useEmbed = true
#Embed Layout to use
embedLayout = "default"

#Control where COMMAND messages are delivered
[messageDestinations.commands]
#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
channel = "CONSOLE"
#Should the message be sent using EMBED style messages
useEmbed = false
#Embed Layout to use
embedLayout = "default"

#Control where messages that match none of the above are delivered
[messageDestinations.custom]
#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
channel = "EVENT"
#Should the message be sent using EMBED style messages
useEmbed = false
#Embed Layout to use
embedLayout = "default"

#Manage access to your server, similar to whitelisting
[accessControl]
#Enable Access Control
enabled = true
#Does the player need to be a member of your discord to join
requireDiscordMembership = true
allowMultipleAccounts = true
#Optional: The player requires any of these roles to be able to join your server
requiredRoles = [
    "01234"
]
#Optional: Players with these roles will never be allowed access to your server
deniedRoles = []
#Optional: Role name or ID to assign to verified player accounts
verifiedRole = "01234"
#Should players with verified accounts, be banned from Minecraft if they get banned on discord
banPlayerOnDiscordBan = true
#Should members with verified accounts, be banned from discord when they are banned on Minecraft
banMemberOnMinecraftBan = false

#Configure messages shown to players when they don't meet verification requirements
[accessControl.verificationMessages]
#The message shown to players that are not verified
accountVerification = "This server requires account verification. Your verification code is: {code}. Please use the /verify command of the Mezacraft Bot in the #survival-chat channel on discord."
#Message to show to players that are not a member of your discord
nonMember = "Sorry, you need to be a member of our discord server to join this server"
#Message to show when player doesn't have one of the required roles. Use {roles} to display the names of configured roles
requireRoles = "Sorry, but you require any of the following roles: {roles}"
#Message to show when player has a role from the deniedRoles list
roleDenied = "Sorry, but you are not allowed to access this server."

#Execute Minecraft commands in Discord
[minecraftCommands]
#Allow executing Minecraft commands from Discord
enabled = false
#Command Prefix. For example ?weather clear
prefix = "?"
#List of command permissions
permissions = []

#Configure messages that will be ignored when relaying to discord
[ignoredMessages]
#Filter certain types of messages from being relayed back to discord
ignoredMessages = true
#List of entries to process
entries = []
#Ignore messages sent from certain threads
ignoredThreads = []

```
