### ISSUE TITLE
[Feature]: `appliesTo = "CONSOLE"` option for filtering

### ISSUE THREAD

**Issue by DorkOrc** [hypherionmc/sdlink#177]
### 🚀 Description

I would like to be able to filter out data from *specifically* the console/"output log" channel. e.g.
```toml
	[[filtering.entries]]
		target = "CONSOLE"
		search = "^\\[net\\.minecraft\\.class_\\d+\\] Serialization errors:[\\s\\S]*"
		replace = ""
		searchMode = "REGEX"
		action = "IGNORE"
		ignoreConsole = false    # I guess ignore this field in this case
		appliesTo = "DISCORD"    # This also implicitly would be DISCORD if the target is CONSOLE, so again could be ignored
```

### 💡 Use Case

This will help
**A)** Prevent potentially sensetive logged data from being sent to the Discord channel
and
**B)** Prevent super long log messages from taking up the entire Discord message which blocks later logs that would have appeared in that block of console logs. (This often happens when a player joins with invalid/outdated NBT data from joining in a snapshot which had a save state that was later changed, so the game dumps the whole broken NBT data to the log which can be very very long).
