### ISSUE TITLE
[Feature Request] Using discord roles and linked player names as variables in custom commands

### ISSUE THREAD

**Issue by j00w33** [hypherionmc/sdlink#71]
Have the ability to use a linked player as a variable for `linkedCommands`

ex:
```toml
[[linkedCommands.commands]]
    mcCommand = "ftbranks add %linkedPlayer% %discordRole%"
    discordCommand = "addrank"
    discordRole = ""
```
