### ISSUE TITLE
[Feature Request] Custom commands triggered on role change.

### ISSUE THREAD

**Issue by j00w33** [hypherionmc/sdlink#77]
In addition to running commands manually through `/mc`, have the option to have it automatically run a certain command based on rule change. "role added and role removed"
With the new features already complete:  
[player variables in commands](https://github.com/hypherionmc/sdlink/issues/71)  
[auto whitelist based on roles](https://github.com/hypherionmc/sdlink/issues/74)  

Would it be difficult to include a custom command to be run when a player role is changed?  
Something like this would be in the config:
```toml
[triggerCommands]
[[triggerCommands.rolechange]]
   enabled = true
   added = true #or false
   #or removed = true/false (some way to determine if the role was added or removed in the command)
   discordRole = "patreoncopper" #this would be the role that triggers the command
   mcCommand = "/ftbranks add %linkedPlayer% %discordRole%" 
# or something more specific
[[triggerCommands.roleadded]]
[[triggerCommands.roleremoved]]
```

It would only work if the player is already whitelisted and linked which would be automated with the aforementioned features. Plus the linked player variables were added too.
